version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      python-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      actions-all:
        patterns:
          - "*"
